//
//  ParameterSelectioinRouter.swift
//  PollutionApp
//
//  Created by Łukasz Drożdż on 01.08.2018.
//  Copyright (c) 2018 Łukasz Drożdż. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ParameterSelectioinRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  func navigateToParameterStats()
  func navigateToAlert(withError error: String)
}

protocol ParameterSelectioinDataPassing
{
  var dataStore: ParameterSelectioinDataStore? { get }
}

class ParameterSelectioinRouter: NSObject, ParameterSelectioinRoutingLogic, ParameterSelectioinDataPassing
{
  weak var viewController: ParameterSelectioinViewController?
  var dataStore: ParameterSelectioinDataStore?
  
  // MARK: Routing
  @objc func routeToParameterStats(segue: UIStoryboardSegue) {
    
    let parameterVC = segue.destination as? StatisticsViewController
    var destDataStore = parameterVC?.router?.dataStore
    passSurveyData(source: dataStore!, destination: &destDataStore!)
  }
  
  // MARK: Navigating
  
  func navigateToParameterStats() {
    viewController?.performSegue(withIdentifier: "ParameterStats", sender: nil)
  }
  
  func navigateToAlert(withError error: String) {
    let alert = UIAlertController(title: "Error", message: error, preferredStyle: .alert)
    alert.addAction(UIAlertAction(title: "Ok", style: .default, handler: { (_ ) in
      self.dismiss()
    }))
    viewController?.present(alert, animated: true, completion: nil)
  }
  
  private func dismiss() {
    viewController?.dismiss(animated: true, completion: nil)
  }
  
  // MARK: Data Passing
  
  private func passSurveyData(source: ParameterSelectioinDataStore, destination: inout StatisticsDataStore) {
    destination.surveyData = source.surveyData
  }
}
