//
//  ParameterSelectioinWorker.swift
//  PollutionApp
//
//  Created by Łukasz Drożdż on 01.08.2018.
//  Copyright (c) 2018 Łukasz Drożdż. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Moya

class ParameterSelectioinWorker
{
  typealias AllStationCompletion = ((SurveyData?, Error?) -> Void)
  
  func doSomeWork()
  {
  }
  
  func fetchSurverData(forSensor sensor: Sensor, completion: @escaping AllStationCompletion) {
    let pollutionProvider = MoyaProvider<PollutionSevice>()
    pollutionProvider.responseCodable(target: PollutionSevice.surveyData(sensorId: sensor.id), type: SurveyData.self) { (data, error) in
      completion(data,error)
    }
  }
}
