//
//  ParameterSelectioinInteractor.swift
//  PollutionApp
//
//  Created by Łukasz Drożdż on 01.08.2018.
//  Copyright (c) 2018 Łukasz Drożdż. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ParameterSelectioinBusinessLogic
{
  func doSomething(request: ParameterSelectioin.Something.Request)
  func displayParams()
  func fetchSurveyData(forSensor sensor: Sensor)
}

protocol ParameterSelectioinDataStore
{
  //var name: String { get set }
  var sensors: [Sensor] { get set }
  var surveyData: SurveyData? { get }
}

class ParameterSelectioinInteractor: ParameterSelectioinBusinessLogic, ParameterSelectioinDataStore
{
  var presenter: ParameterSelectioinPresentationLogic?
  var worker: ParameterSelectioinWorker?
  //var name: String = ""
  var sensors: [Sensor] = []
  var surveyData: SurveyData?
  
  // MARK: Do something
  
  func displayParams() {
    presenter?.presentParameters()
  }
  
  func fetchSurveyData(forSensor sensor: Sensor) {
    worker?.fetchSurverData(forSensor: sensor, completion: { (data, error) in
      if let error = error {
        self.presenter?.presentError(withDescription: error.localizedDescription)
        return
      }
      
      if let surveyData = data {
        self.surveyData = surveyData
        self.presenter?.presentStatistiscForParam()
      }
    })
  }
  
  func doSomething(request: ParameterSelectioin.Something.Request)
  {
    worker = ParameterSelectioinWorker()
    worker?.doSomeWork()
    
    let response = ParameterSelectioin.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
