//
//  StatisticsInteractor.swift
//  PollutionApp
//
//  Created by Łukasz Drożdż on 01.08.2018.
//  Copyright (c) 2018 Łukasz Drożdż. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StatisticsBusinessLogic
{
  func doSomething(request: Statistics.Something.Request)
  func displayStatistcs()
}

protocol StatisticsDataStore
{
  //var name: String { get set }
  var surveyData: SurveyData? { get set }
  
}

class StatisticsInteractor: StatisticsBusinessLogic, StatisticsDataStore
{
  var presenter: StatisticsPresentationLogic?
  var worker: StatisticsWorker?
  //var name: String = ""
  var surveyData: SurveyData?
  
  // MARK: Do something
  
  func doSomething(request: Statistics.Something.Request)
  {
    worker = StatisticsWorker()
    worker?.doSomeWork()
    
    let response = Statistics.Something.Response()
    presenter?.presentSomething(response: response)
  }
  
  func displayStatistcs() {
    presenter?.presentStats(forSurvey: surveyData)
}
}
