//
//  StatisticsPresenter.swift
//  PollutionApp
//
//  Created by Łukasz Drożdż on 01.08.2018.
//  Copyright (c) 2018 Łukasz Drożdż. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Charts

protocol StatisticsPresentationLogic
{
  func presentSomething(response: Statistics.Something.Response)
  func presentStats(forSurvey survey: SurveyData?)
}

class StatisticsPresenter: StatisticsPresentationLogic
{
  weak var viewController: StatisticsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Statistics.Something.Response)
  {
    let viewModel = Statistics.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
  
  func presentStats(forSurvey survey: SurveyData?) {
    
    viewController?.displayChart(forData: generateChartData(fromSurvey: survey))
  }
  
  private func generateChartData(fromSurvey survey: SurveyData?) -> LineChartData? {
    guard let survey = survey else {
      return nil
    }
    var lineChartEntry = [ChartDataEntry]()
    
  
    survey.values.enumerated().forEach { (index,value) in
      if let notNilValue = value.value {
        
        let dataEntry = ChartDataEntry(x: Double(index), y: notNilValue)
        lineChartEntry.append(dataEntry)
      }
    }
    
    let line1 = LineChartDataSet(values: lineChartEntry, label: "\(survey.key)")
    line1.drawCirclesEnabled = false
    line1.colors = [UIColor.blue]
    let data = LineChartData()
    data.addDataSet(line1)
    return data
  }
}
