//
//  HomeWorker.swift
//  PollutionApp
//
//  Created by Łukasz Drożdż on 30.07.2018.
//  Copyright (c) 2018 Łukasz Drożdż. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Moya

class HomeWorker
{
	typealias AllStationCompletion = (([Station]?, Error?) -> Void)
	typealias SensorsCompletion = (([Sensor]?, Error?) -> Void)
	
	func fetchAllStations(completion: @escaping AllStationCompletion) {
		let pollutionProvider = MoyaProvider<PollutionSevice>()
		
		pollutionProvider.responseCodable(target:PollutionSevice.findAllStations,  type: [Station].self) { (allStations, error) in
			completion(allStations,error)
		}
	}
	
	func fetchSensors(forStation station: Station, completion: @escaping SensorsCompletion) {
		let pollutionProvider = MoyaProvider<PollutionSevice>()
		pollutionProvider.responseCodable(target: PollutionSevice.sensors(stationId: station.id), type: [Sensor].self) { (sensors, error) in
			completion(sensors,error)
		}
	}
}
