//
//  HomeRouter.swift
//  PollutionApp
//
//  Created by Łukasz Drożdż on 30.07.2018.
//  Copyright (c) 2018 Łukasz Drożdż. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic
{
	func navigateToAlert(withError error: String)
	func navigateToStationSelection()
	func navigateToParemeterSelection()
	
}

protocol HomeDataPassing
{
  var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing
{
  weak var viewController: HomeViewController?
  var dataStore: HomeDataStore?
  
  // MARK: Routing
	
	@objc func routeToShowStationSelection(segue: UIStoryboardSegue) {
		let selectionVC = segue.destination as! StationSelectionViewController
		// Assign delegate for station selection
		selectionVC.delegate = viewController
		var destinationDataStore = selectionVC.router?.dataStore
		passDataToSelection(source: dataStore!, destination: &destinationDataStore!)
	}
	
	@objc func routeToSensorSelection(segue: UIStoryboardSegue) {

		let parameterVC = segue.destination as? ParameterSelectioinViewController
		var destDataStore = parameterVC?.router?.dataStore
		passSensorsForParamSelection(soruce: dataStore!, destination: &destDataStore!)
	}
	
	// MARK: Navigating
	
	func navigateToStationSelection() {
		viewController?.performSegue(withIdentifier: "ShowStationSelection", sender: nil)
	}
	
	func navigateToParemeterSelection() {
		viewController?.performSegue(withIdentifier: "SensorSelection", sender: nil)
	}
	
	func navigateToAlert(withError error: String) {
		let alert = UIAlertController(title: "Error", message: error, preferredStyle: .alert)
		alert.addAction(UIAlertAction(title: "Ok", style: .default, handler: { (_ ) in
			self.dismiss()
		}))
		viewController?.present(alert, animated: true, completion: nil)
	}
	
	private func dismiss() {
		viewController?.dismiss(animated: true, completion: nil)
	}
	
	// MARK: Data Passing
	
	private func passDataToSelection(source: HomeDataStore, destination: inout StationSelectionDataStore) {
		destination.stations = source.stations
	}
	
	private func passSensorsForParamSelection(soruce: HomeDataStore, destination: inout ParameterSelectioinDataStore) {
		destination.sensors = soruce.sensorsInCity
	}
	
}
