//
//  HomePresenter.swift
//  PollutionApp
//
//  Created by Łukasz Drożdż on 30.07.2018.
//  Copyright (c) 2018 Łukasz Drożdż. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
	func presentError(withDescription description: String)
	func presentSuccess()
	func presentSearchedCities()
	func presentSensorsSuccess()

}

class HomePresenter: HomePresentationLogic
{
	weak var viewController: HomeDisplayLogic?
	
	// MARK: Do something
	
	func presentError(withDescription description: String) {
		viewController?.presentAlert(forError: description)
	}
	
	func presentSuccess() {
		viewController?.presentSuccess()
	}
	
	func presentSearchedCities() {
		viewController?.presentSuccess()
	}
	
	func presentSensorsSuccess() {
		viewController?.presentSensorsSuccess()
	}
}
