//
//  StationSelectionInteractor.swift
//  PollutionApp
//
//  Created by Łukasz Drożdż on 01.08.2018.
//  Copyright (c) 2018 Łukasz Drożdż. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StationSelectionBusinessLogic
{
  func doSomething(request: StationSelection.Something.Request)
  func showStationsForCity()
}

protocol StationSelectionDataStore
{
  //var name: String { get set }
  var stations: [Station] { get set }
    
}

class StationSelectionInteractor: StationSelectionBusinessLogic, StationSelectionDataStore
{
 
  
  var presenter: StationSelectionPresentationLogic?
  var worker: StationSelectionWorker?
  var stations: [Station] = []
  //var name: String = ""
  
  // MARK: Do something
  
  func showStationsForCity() {
    presenter?.presentStationsForCity()
  }
  
  func doSomething(request: StationSelection.Something.Request)
  {
    worker = StationSelectionWorker()
    worker?.doSomeWork()
    
    let response = StationSelection.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
