//
//  StationSelectionRouter.swift
//  PollutionApp
//
//  Created by Łukasz Drożdż on 01.08.2018.
//  Copyright (c) 2018 Łukasz Drożdż. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol StationSelectionRoutingLogic
{
  func dismiss()
}

protocol StationSelectionDataPassing
{
  var dataStore: StationSelectionDataStore? { get }
}

class StationSelectionRouter: NSObject, StationSelectionRoutingLogic, StationSelectionDataPassing
{
  weak var viewController: StationSelectionViewController?
  var dataStore: StationSelectionDataStore?
  
  // MARK: Routing
  
  func dismiss() {
    viewController?.dismiss(animated: true, completion: nil)
  }
}
